# ╔═════════════════════════════════════════════════════════════════════════════════════╗
# ║                          Наш телеграм канал                                         ║
# ║                          t.me/spacestudiomc                                         ║
# ╚═════════════════════════════════════════════════════════════════════════════════════╝
# ╔═════════════════════════════════════════════════════════════════════════════════════════════╗
# ║  ███████╗██████╗  █████╗  ██████╗███████╗    ███████╗████████╗██╗   ██╗██████╗ ██╗ ██████╗  ║
# ║  ██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝    ██╔════╝╚══██╔══╝██║   ██║██╔══██╗██║██╔═══██╗ ║
# ║  ███████╗██████╔╝███████║██║     █████╗      ███████╗   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
# ║  ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝      ╚════██║   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
# ║  ███████║██║     ██║  ██║╚██████╗███████╗    ███████║   ██║   ╚██████╔╝██████╔╝██║╚██████╔╝ ║
# ║  ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝    ╚══════╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝ ╚═════╝  ║
# ╚═════════════════════════════════════════════════════════════════════════════════════════════╝
#
#                               ╔════════════════════════════════════╗
#                               ║         Кодер - m0onmag            ║
#                               ║         t.me/m0onmag               ║
#                               ╚════════════════════════════════════╝

name: SpaceLastPay
version: '1.2'
main: ru.moonmag.SpaceLastPay
api-version: '1.16'
author: [ SpaceDev ]